`timescale 1ns / 1ps

module fir_filter_tb;

    // 1. UUT Signals
    reg clk;
    reg rst_n;
    reg signed [15:0] x_in;
    wire signed [15:0] y_out;

    // 2. Memory Arrays for File I/O
    // Adjust NUM_SAMPLES to match however many samples your teammate generates in MATLAB
    parameter NUM_SAMPLES = 1000;
    
    reg signed [15:0] stimulus_mem [0:NUM_SAMPLES-1];
    reg signed [15:0] golden_mem   [0:NUM_SAMPLES-1];

    integer i;
    integer error_count;

    // Instantiate the Device Under Test (DUT)
    fir_filter dut (
        .clk(clk),
        .rst_n(rst_n),
        .x_in(x_in),
        .y_out(y_out)
    );

    // 3. Clock Generation
    initial begin
        clk = 0;
        forever #5 clk = ~clk; // 10ns period (100 MHz simulation clock)
    end

    // 4. Main Test Sequence
    initial begin
        // Initialize
        x_in = 16'sh0000;
        error_count = 0;
        
        // Load the hex files generated by MATLAB using $readmemh
        $readmemh("stimulus_case1.hex", stimulus_mem);
        $readmemh("golden_case1.hex", golden_mem);

        // Assert Reset
        rst_n = 0;
        #20;
        
        // Release Reset
        rst_n = 1;
        #20;

        // 5. Drive Samples and Verify
        $display("Starting simulation...");
        
        for (i = 0; i < NUM_SAMPLES; i = i + 1) begin
            // Drive the input sample on the negative edge to ensure stable setup time
            @(negedge clk);
            x_in = stimulus_mem[i];
            
            // Wait for the positive edge where the DUT processes the input
            @(posedge clk);
            #1; // Small delay to let the y_out register update on the waveform
            
            
            $display("Sample %4d | x_in: %d | y_out: %d | Golden: %d", 
                     i, x_in, y_out, golden_mem[i]);
                     
            if (y_out !== golden_mem[i]) begin
                error_count = error_count + 1;
            end
        end

        $display("Simulation complete. Total mismatches: %d", error_count);
        $stop;
    end

endmodule